name: "PyTach"
description: "Send IR and RF with iTach device"
version: "0.1.0"
slug: "pytach"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ingress: true
ports:
  8099/tcp: 8000

